# Generated by Django 4.1.7 on 2023-03-23 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='status',
        ),
        migrations.AddField(
            model_name='company',
            name='VIP_status',
            field=models.CharField(blank=True, choices=[('3 day', ' 3 day / 2,00 AZN'), ('15 day', '15 day / 8,00 AZN'), ('1 month', ' 1 month / 18,00 AZN')], max_length=40, null=True),
        ),
    ]
