# Generated by Django 4.1.7 on 2023-03-25 07:11

from django.db import migrations, models
import services.uploader


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_alter_company_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=services.uploader.Uploader.upload_logo_game_company),
        ),
    ]
