# Generated by Django 4.1.7 on 2023-03-26 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_alter_company_icon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='description',
            new_name='bio',
        ),
    ]
