# Generated by Django 4.1.7 on 2023-03-30 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_rename_description_company_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='mobile',
        ),
    ]
