# Generated by Django 4.1.7 on 2023-03-23 09:36

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import services.uploader


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('code', models.SlugField(editable=False, unique=True)),
                ('name', models.CharField(max_length=40)),
                ('icon', models.ImageField(blank=True, null=True, upload_to=services.uploader.Uploader.upload_logo_game_category)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='games.category')),
            ],
            options={
                'verbose_name': 'Game Category',
                'verbose_name_plural': 'Game Categories',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='GameAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('code', models.SlugField(editable=False, unique=True)),
                ('name', models.CharField(max_length=40)),
                ('status', models.CharField(choices=[('Racing', 'Racing'), ('MOBA', 'MOBA'), ('Simulation and sports', 'Simulation and sports'), ('FPS', 'FPS'), ('RPG', 'RPG')], max_length=50)),
                ('description', ckeditor.fields.RichTextField()),
                ('price', models.PositiveIntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.category')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
            ],
            options={
                'verbose_name': 'Game Account',
                'verbose_name_plural': 'Game Accounts',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='GameAccountGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('code', models.SlugField(editable=False, unique=True)),
                ('image', models.ImageField(upload_to=services.uploader.Uploader.upload_image_game)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.gameaccount')),
            ],
            options={
                'verbose_name': 'Game Account Gallery',
                'verbose_name_plural': 'Game Accounts Galleries',
                'ordering': ('-created_at',),
            },
        ),
    ]
