# Generated by Django 4.1.7 on 2023-03-23 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameaccountgallery',
            name='code',
        ),
        migrations.RemoveField(
            model_name='gameaccountgallery',
            name='slug',
        ),
    ]
