# Generated by Django 4.1.7 on 2023-03-29 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_alter_category_slug_alter_gameaccount_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameaccount',
            name='status',
        ),
        migrations.AddField(
            model_name='gameaccount',
            name='type',
            field=models.CharField(blank=True, choices=[('Racing', 'Racing'), ('MOBA', 'MOBA'), ('Simulation and sports', 'Simulation and sports'), ('FPS', 'FPS'), ('RPG', 'RPG')], max_length=50, null=True),
        ),
    ]
