# Generated by Django 4.1.7 on 2023-03-30 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_remove_gameaccount_status_gameaccount_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameaccount',
            name='type',
            field=models.CharField(blank=True, choices=[('', '--------Type'), ('Racing', 'Racing'), ('MOBA', 'MOBA'), ('Simulation and sports', 'Simulation and sports'), ('FPS', 'FPS'), ('RPG', 'RPG')], max_length=50, null=True),
        ),
    ]
