# Generated by Django 4.1.7 on 2023-03-30 11:34

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_alter_gameaccount_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameaccount',
            name='mobile',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
