# Generated by Django 4.1.7 on 2023-03-31 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_gameaccount_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameaccount',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
