# Generated by Django 4.1.7 on 2023-04-06 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='code',
        ),
        migrations.RemoveField(
            model_name='basket',
            name='slug',
        ),
    ]
