# Generated by Django 4.1.7 on 2023-04-06 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_review_user'),
        ('basket', '0002_remove_basket_code_remove_basket_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='gameacc',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='games.gameaccount'),
        ),
    ]
